apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: spring-petclinic-db
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: spring-petclinic
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-petclinic
spec:
  name: db
  service:
    apiVersion: sql.tanzu.vmware.com/v1
    kind: Postgres
    name: postgres-db
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: spring-petclinic

